config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  root "messages#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_message
    before_action :find_comment, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def create
        @comment = @message.comments.create(comment_params)
        @comment.user_id = current_user.id
        respond_to do |format|
        if @comment.save
            format.html { redirect_to message_path(@message), :notice => 'Comment was successfully created !' } 
        else
            render 'new'
        end
    end
    end

    def edit
        
    end

    def update
        respond_to do |format|
        if @comment.update(comment_params)
            format.html { redirect_to message_path(@message), :notice => 'Comment was successfully updated !' } 
        else
            render 'edit'
        end
    end
    end

    def destroy
        respond_to do |format|
            @comment.destroy
                format.html { redirect_to message_path(@message), :notice => 'Comment was successfully deleted !' } 
            end
    end

    private

      def comment_params
        params.require(:comment).permit(:content)
      end

      def find_message
        @message = Message.find(params[:message_id])
      end

      def find_comment
        @comment = @message.comments.find(params[:id])
      end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :find_message, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @messages = Message.all.order("created_at DESC")
    end
    
    def new
        @message = current_user.messages.build
    end
    
    def show
        
    end
    
    def create
        @message = current_user.messages.build(message_params)
        respond_to do |format|
        if @message.save
            format.html { redirect_to root_path, :notice => 'Message was successfully created !' } 
        else
            render 'new'
        end
    end
    end

    def edit
    end

    def update
        respond_to do |format|
        if @message.update(message_params)
            format.html { redirect_to root_path, :notice => 'Message was successfully updated !' } 
        else
            render 'edit'
        end
    end
    end

    def destroy
        respond_to do |format|
        @message.destroy
            format.html { redirect_to root_path, :notice => 'Message was successfully deleted !' } 
        end
    end
    
    private

    def message_params
        params.require(:message).permit(:title, :description)
    end

    def find_message
        @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="border border-1 border-secondary p-3 my-2" style="border-radius:15px;">

<div class="mt-2"> 
    <p style="color:white;"> <%= comment.content %> </p>
    <span style="color:#0B5ED7;">Posted By <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago.</span>
</div>


<%if user_signed_in?%>
    <%if comment.user.id == current_user.id%>
        <div class = "d-flex mt-1">
            <%= link_to "Edit This Comment", edit_message_comment_path(comment.message,comment), class: "btn btn-success mx-1"%>  
            <%= button_to "Delete This Comment", message_comment_path(comment.message,comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, 
            class: "btn btn-danger mx-1"%>
        </div>
    <%end%>
<%end%>

</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message,@message.comments.build]) do |f|%>
    <div class="mt-3 d-flex flex-column" style="width:25rem;">
        <%= f.input :content, label: false, placeholder: "please write your comment here...", class: "mt-2", :input_html => {:rows => 2}%>
        <%= f.button :submit, class: "btn btn-primary mt-2"%>
    </div>
<%end%>

app/views/comments/edit.html.erb
<h2 class="text-center fw-bold mt-5"> Edit Comment </h2>
<%= simple_form_for([@message,@comment]) do |f|%>
    <div class="container-lg mt-3 d-flex flex-column">
        <%= f.input :content, label: false,placeholder: "please write your content here...", class: "mt-2", :input_html => {:rows => 3}%>
        <%= f.button :submit, class: "btn btn-primary mt-2"%>
        <%= link_to "Back To The Message", message_path(@message), class: "btn btn-secondary mt-2"%>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Message Board", root_path, class: "navbar-brand fw-bold fs-3 ms-2 "%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item" style="color:white;!important">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link fw-bold fs-5 ms-2"%>
        </li>
        <%if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link fw-bold fs-5 ms-2"%>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item text-decoration-underline">
          <%= link_to "New Message", new_message_path, class: "nav-link fw-bold fs-5"%>
        </li>
      </ul>
      <%else%>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link fw-bold fs-5 ms-2"%>
        </li>
      </ul>
      <%end%>
    </div>
  </div>
</nav>
    <%if notice%>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong class="notice"><%= notice %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%end%>    
    <%if alert%>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong class="alert"><%= alert %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <%end%>

    <%= yield %>

     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <div class="container-lg mt-3 d-flex flex-column">
    <%= f.input :title, label: false, placeholder: "please write your title here...", class: "mt-2", :input_html => {:rows => 3}%>
    <%= f.input :description, label: false, placeholder: "please write your description here...", class: "mt-2", :input_html => {:rows => 5}%>
    <%= f.button :submit,  class: "btn btn-primary mt-2"%>
    <%= link_to "Back To Messages", root_path, class: "btn btn-secondary mt-2"%>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h2 class="text-center fw-bold mt-5"> Edit Message </h2>
<%= render 'form'%>

app/views/messages/index.html.erb
<div class="row ms-auto me-auto mt-5"> 
    <% @messages.each do |message|%>
        <div class="col-lg-4 p-2 border border-3 border-light rounded-end d-flex flex-column justify-content-evenly" style="background-color:#6C757D;">
            <h2 class="text-center" style="color:white; opacity:90%;"><%= message.title%></h2>
            <p class="ms-3 button-card"><%= link_to "View Message", message_path(message), class:"button-link"%></p>
        </div>
    <%end%>
</div>

app/views/messages/new.html.erb
<h2 class="text-center fw-bold mt-5"> New Message </h2>
<%= render 'form' %>

app/views/messages/show.html.erb
<div class="container-lg mt-5 p-5" style="background-color:#a9aeb2; border-radius:10px;">
    <h2 class="fs-1 fw-bold"><%= @message.title%></h2>
    <p class="pt-2 ms-3"><%= @message.description%><p>
    <p class="text-end" style="color:#0B5ED7;">Posted By <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago.<p>
    
    <div class="border border-1 border-secondary p-3 mt-5" style="border-radius:15px;">
        
        <h3 class="mt-5 fs-2 fw-bold"> Comments :  </h3>
        <%= render @message.comments%>


        <h3 class="mt-5 fs-2 fw-bold"> Reply That Message : </h3>
        <%= render 'comments/form'%>

    </div>

    <div class = "d-flex justify-content-between mt-5">
    <%= link_to "Back to Messages", root_path, class: "btn btn-primary"%>
    <%if user_signed_in?%>
        <%if @message.user.id == current_user.id%>
        <%= link_to "Edit This Message ", edit_message_path(@message), class: "btn btn-success"%>
        <%= button_to "Delete This Message", message_path(@message), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, 
        class: "btn btn-danger"%>
        <%end%>
    <%end%>
    </div>
</div>